import type { Chapter } from "@/lib/film";

export const PROCESS_CHAPTERS: Chapter[] = [
  {
    id: "pick",
    last: "The pair",
    why: "Tap the shoe you want. Photos swipe.",
    title: "Pick the pair you like.",
    line: "Vellies, golfers, chelseas, boots. The price on the card is the pair. Extras are extra — R50 each. Laces, stitch, elastic, sole, lining, hardware, laser.",
    meta: "Made in South Africa",
    still: "/film/book.jpg",
    video: "/film/book.mp4",
  },
  {
    id: "order",
    last: "Send",
    why: "Name and WhatsApp. We reply.",
    title: "Send it to us.",
    line: "Pick UK size (we show EU too) and hide. Grey hide, aqua stitch, black laces, a laser — tell the spec clerk, or write it on the pair. Then send. We WhatsApp you on the number you gave.",
    meta: "Pay after we confirm",
    still: "/film/order.jpg",
    video: "/film/order.mp4",
  },
  {
    id: "confirm",
    last: "Confirm",
    why: "We check the bench. Then you pay.",
    title: "We confirm. Then EFT.",
    line: "If the pair is there, we send the listed rand. You pay. That is when the pair is yours — not before.",
    meta: "Confirm, then pay",
    still: "/film/confirm.jpg",
    video: "/film/confirm.mp4",
  },
  {
    id: "make",
    last: "Make",
    why: "Cut, stitch, finish here.",
    title: "We make it here.",
    line: "Once paid, most pairs leave in 10–14 working days. Handmade in our factory in South Africa.",
    meta: "10–14 working days after pay",
    still: "/film/cut.jpg",
    video: "/film/cut.mp4",
  },
  {
    id: "laser",
    last: "Laser",
    why: "Outside only. R50.",
    title: "A mark on the outside.",
    line: "Heel, quarter, or vamp. Initials, a name, or a logo. R50. Logo we confirm before we burn.",
    meta: "R50  ·  Outside only",
    still: "/film/laser.jpg",
    video: "/film/laser.mp4",
  },
  {
    id: "send",
    last: "Leave",
    why: "Collect free. SA R100. Abroad R300.",
    title: "Collect, or we send.",
    line: "Close enough? Collect, no fee. In South Africa we send for R100. Abroad R300.",
    meta: "Collect  ·  SA R100  ·  Abroad R300",
    still: "/film/send.jpg",
    video: "/film/send.mp4",
  },
];
